name: Demo1
on: [push]
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4
        
      -name: list all the files and folders of the repo
       run: ls -lart
